### ISSUE TITLE
Segmentation fault when using a specific RegEx pattern

### ISSUE THREAD

**Issue by Sclarki** [ggreer/the_silver_searcher#644]
I was testing out various patterns and noticed that AG segfaults when using one of the following:

    $ ./ag '(.|\n)*'
    $ ./ag '(.|\s)*'
    $ ./ag '(\s|\S)*'
    $ ./ag '(\s|\S|\n)*'

I tested these in the AG repo (root directory) with no modifications to the source, aside from changes to the highlight colour in ```options.c```. Also, there's no specific point that this happens during the search as it'll segf in any file. It seems to occur the same way in other directories, as well.

This isn't a hinderance for me specifically, but out of curiosity, is this a bug, or just an improper use case?

**Comment by ggreer** [comment]
All of those work fine for me. Can you give more information about the test data, version of ag, platform, etc?

**Comment by Sclarki** [comment]
It'll happen on any file, whether it's source code from directories for Git, AG, Screen, GCC, or other files like ACME shopping lists and poems about cybernetic injustice. It doesn't seem to have a specific file that it _prefers_ faulting on. Just now I found out it'll have the exact same behaviour for images if I use the --unrestricted switch.

Current versions and details are:

* Ubuntu 14.04.2 LTS, Unity DE, 64-bit
* AG 0.29.1
* Terminator 0.97 (same result with GNOME Terminal 3.6.2 and XTerm 297)

Hope I'm not forgetting something.

**Comment by ggreer** [comment]
Do you have a core dump or at backtrace or something? I really can't reproduce this, and I think it may be a problem with your specific computer. More people would be complaining if such a simple regex reliably caused segfaults.

**Comment by Sclarki** [comment]
I really don't know if this will be useful (definitely not something I do everyday, sorry), but I've turned up this to try and find what you're asking.

https://www.dropbox.com/s/etj06542o1w8hdq/core.tar.gz?dl=0
https://www.dropbox.com/s/hz83gn4efi8v45r/gdb-ag.txt.tar.gz?dl=0

The only thing I see that is connected in all of that (in gdb-ag) is it spitting out some problem with pcre_exec.c.

**Comment by Mandar12** [comment]
I also tried first pattern. It crashes every time. The core info :
Core was generated by `./ag (.|\n)*'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000339c40ff82 in ?? () from /lib64/libpcre.so.0

(gdb) bt -8
#18194 0x000000339c410249 in ?? () from /lib64/libpcre.so.0
#18195 0x000000339c4113f6 in ?? () from /lib64/libpcre.so.0
#18196 0x000000339c418812 in pcre_exec () from /lib64/libpcre.so.0
#18197 0x0000000000406c81 in search_buf (
    buf=0x7f7255bc6000 <Address 0x7f7255bc6000 out of bounds>, buf_len=86016, 
    dir_full_path=0x7f725855aff4 "./crash.txt") at src/search.c:96
#18198 0x0000000000407053 in search_file (
    file_full_path=0x7f725855aff4 "./crash.txt") at src/search.c:287
#18199 0x00000000004072da in search_file_worker (i=Unhandled dwarf expression opcode 0xf3
) at src/search.c:325
#18200 0x000000338dc079d1 in start_thread (arg=0x7f7257add700)
    at pthread_create.c:301
#18201 0x000000338d8e88fd in clone () from /lib64/libc.so.6

In frame 18197, buf address is out of bounds.

**Comment by ggreer** [comment]
Do *any* regex patterns work for you guys? It's as if you've built against a different version of libpcre than the one that's getting loaded at runtime.

**Comment by Mandar12** [comment]
Operating system : Ubuntu 14.04 (64 bit),  Linux 3.13
ag version       : 0.30.0  Features:  +jit +lzma +zlib
pcre                 : libpcre3-dev
mandar@ubuntu:~$ apt-cache policy libpcre3-dev libpcre3:amd64
libpcre3-dev:
  Installed: 1:8.31-2ubuntu2
  Candidate: 1:8.31-2ubuntu2
  Version table:
 *** 1:8.31-2ubuntu2 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
